START_LOC_SOLDIER = 1 #temp
START_LOC_FLAG = 2 #temp

BOARD_ROWS = 25
BOARD_COLUMNS = 50
SQUARE_SIZE = 15
WINDOW_WIDTH = BOARD_COLUMNS * SQUARE_SIZE
WINDOW_LENGTH = BOARD_ROWS * SQUARE_SIZE
GREEN_COLOR = (6, 140, 48)