START_LOC_SOLDIER = 1 #temp
START_LOC_FLAG = 2 #temp

NUM_OF_ROWS = 25
NUM_OF_COLS = 50
SQUARE_SIZE = 15
WINDOW_WIDTH = NUM_OF_COLS * SQUARE_SIZE
WINDOW_LENGTH = NUM_OF_ROWS * SQUARE_SIZE
GREEN_COLOR = (6, 140, 48)

LOSE_STATE = 1
WIN_STATE = 3
RUNNING_STATE = 2
BOMB_IMG = "bomb.png"
