START_LOC_SOLDIER = 1 #temp
START_LOC_FLAG = 2 #temp
SOLDIER_PIC_LOC_X = 0
SOLDIER_PIC_LOC_Y = 0

BOARD_ROWS = 25
BOARD_COLUMNS = 50
SQUARE_SIZE = 15
WINDOW_WIDTH = BOARD_COLUMNS * SQUARE_SIZE
WINDOW_LENGTH = BOARD_ROWS * SQUARE_SIZE
GREEN_COLOR = (6, 140, 48)

GRASS_IMG = "grass.png"


LOSE_STATE = 1
WIN_STATE = 3
RUNNING_STATE = 2
MINE_IMG = "mine.png"
GRASS_IMG = "grass.png"